---
- name: Create new backup policy and associate worflow

  uri:
    url: https://10.241.216.134:9090/nwrestapi/v3/global/protectionpolicies
    validate_certs: false
    user: "{{username}}"
    password: "{{password}}"
    headers:
      Content-Type: "application/json"
    method: POST
    body:
      name: "{{new_policy_name}}"
      workflows:
        - autoStartEnabled: false
          description: "Traditional Backup to pool Default, with expiration 1 Months;"
          name: "{{new_workflow_name}}"
          protectionGroups:
            - "{{protection_group}}"
    body_format: json
    status_code:
      - 201
      - 400
  register: response

- debug: var=response

- fail:
    msg: "Playbook failed There is already a Protection Policy with name {{new_policy_name}}"
- fail:
    msg: "Failed to create new backup policy"
  when: response.status != 201

- debug: 
    msg: "Successfully created new backup policy."
  when: response.status == 201