---
- name: create new protection group

  uri:
    url: https://10.241.216.134:9090/nwrestapi/v1/global/protectiongroups
    validate_certs: false
    user: "{{username}}"
    password: "{{password}}"
    headers:
      Content-Type: "application/json"
    method: POST
    body:
      name: "{{protection_group}}"
    body_format: json
    status_code:
      - 201
  register: response

- debug: var=response

- debug: 
    msg: "New protection group is created successfully."
  when: response.status == 201

- include_tasks: create_new_policy.yml
  when: response.status == 201

- fail:
    msg: "Failed to create new protection group in the srever."
  when: response.status != 201
