---
- name: protection group validation

  uri:
    url: https://{{endpoint}}:9090/nwrestapi/v1/global/protectiongroups/{{protection_group}}
    validate_certs: false
    user: "{{username}}"
    password: "{{password}}"
    headers:
      Content-Type: "application/json"
    method: GET
    body_format: json
    status_code:
      - 200
      - 404
  register: response

- debug: var=response

- debug: 
    msg: "Specified protection group does not exists in the server."
  when: response.status == 404
  
- include_tasks: create_new_group.yml
  when: response.status == 404

- include_tasks: create_new_policy.yml
  when: response.status == 200