---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - include_vars: ../vars/var.yml

    - name: Adding client to a specific policy
      uri: 
        url: https://{{endpoint}}:9090/nwrestapi/v1/global/protectiongroups/Silver-Application
        method: GET
        user: "{{username}}"
        password: "{{password}}"
        validate_certs: no
        headers:
          Accept: "application/json"
        body_format: json            
        status_code: 401,202,200
      register: output
    - debug: var=output

    - set_fact: 
        workItems: "{{output.json.workItems}}"

    #validation for attaching policy to a client
    - debug: 
        msg: "Client is already added to existing policy."
      when: item in workItems
      with_items: "{{clientId}}"

    #Adding client to policy 
    - set_fact: 
        workItems: "{{ workItems + [item] }}"
      with_items: "{{clientId}}"
    - debug: var=workItems

    # Validation for removing client from a policy
    # - debug:
    #     msg: "Client doest not exists in the policy to remove"
    #   when: item not in workItems
    #   with_items: "{{clientId}}" 
      
    # # Remove client from policy
    # - set_fact: 
    #     workItems: "{{ workItems | reject('search', item) | list }}"
    #   with_items: "{{clientId}}"
    # - debug: var=workItems

    - name: Removng client from a specific policy
      uri: 
        url: https://{{endpoint}}:9090/nwrestapi/v1/global/protectiongroups/Silver-Application
        method: PUT
        user: "{{username}}"
        password: "{{password}}"
        validate_certs: no
        headers:
          Accept: "application/json"
        body:
          workItems: "{{ workItems }}"
        body_format: json            
      register: output
    - debug: var=output

