---
- name: Networker Client Details
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - include_vars: vars/var.yml
    - include_vars: vars/locations.yml

    - set_fact: 
        endpoint: "{{item.server_ip}}"
        username: "{{item.username}}"
        password: "{{item.password}}"
      when: item.server_name == location_name
      with_items: "{{location}}"
    - debug:
        msg:
         - "{{endpoint}}"
         - "{{username}}"
         - "{{password}}"
    - import_tasks: create_delete_backup_policy/protection_group_validation.yml
    # - import_tasks: create_delete_backup_policy/create_new_policy.yml
