---
- name: Networker Client Details
  hosts: localhost
  connection: local
  gather_facts: no
<<<<<<< HEAD
  vars: 
    protection_groups: []
    protection_group_list: []
=======
>>>>>>> 90fc5fbe8fc6d0735ff1c9b52194e6b16b6147c5

  tasks:
    - include_vars: vars.yml
    - include_vars: locations.yml

    - set_fact:
        client_name: "{{ client }}"

    - debug: 
        msg: "{{client_name}}"

    - debug: 
        msg: "{{item}}"
      with_items: "{{location}}"

    - name: Networker Client Details REST call using URI to get information from Networker API
      uri:
        url: "https://{{item.server_ip}}:9090/nwrestapi/v3/global/clients?q=hostname:'{{client_name}}'"
        validate_certs: false
        user: "{{item.username}}"
        password: "{{item.password}}"
        headers:
          Content-Type: "application/json"
        method: GET
        body_format: json
        status_code:
          - 200
      with_items: "{{location}}"
      register: response

    - debug: 
        var: response

    - name: Filtering the result
      set_fact: 
         protection_group_list: "{{ protection_group_list + item.json.clients}}"
      with_items: "{{response.results}}"

    - debug:
        msg: "Clients List: {{ protection_group_list }}"

    - set_fact:
        protection_group_count: "{{protection_group_list | length}}"

    - debug: var=protection_group_count
    
    - block:
      - name: "End play if no protection policy is found for Client"
        debug:
          msg: "Failed to list the protection policy for the given client as it does not exist in any of the locations."

      - meta: end_play
      when: protection_group_count|int == 0

    - name: Combining the Protection Groups results from all the locations
      set_fact: 
        protection_groups: "{{ protection_groups + item.protectionGroups }}"
      with_items: "{{protection_group_list}}"

    - debug:
        msg: "List of Protection Groups of the Client: {{ protection_groups }}"

    - debug:
        var: protection_groups