---
- name: On-demand backup
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - include_vars: vars/var.yml
    - include_vars: vars/locations.yml

    - set_fact: 
        endpoint: "{{item.server_ip}}"
        username: "{{item.username}}"
        password: "{{item.password}}"
      when: item.server_name == location_name
      with_items: "{{location}}"

    - debug:
        msg:
         - "{{endpoint}}"
         - "{{username}}"
         - "{{password}}"
         
    - import_tasks: on_demand_backup/initiate_ondemand_backup.yml
    