---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - include_vars: ../vars/var.yml
    - include_vars: ../vars/locations.yml
    
    - set_fact: 
        endpoint: "{{item.server_ip}}"
        username: "{{item.username}}"
        password: "{{item.password}}"
      when: item.server_name == location_name
      with_items: "{{location}}"

    - include_tasks: fetch_clientId.yml

    - name: Adding client to a specific policy
      set_fact: 
        protection_group: "{{policy_info.protectionGroups[0]}}"

    - debug: var="{{protection_group}}"

    - name: Fetch protection group details
      uri: 
        url: https://{{endpoint}}:9090/nwrestapi/v3/global/protectiongroups/{{protection_group}}
        method: GET
        user: "{{username}}"
        password: "{{password}}"
        validate_certs: no
        headers:
          Accept: "application/json"
        body_format: json            
        status_code: 401,200
      register: output
    - debug: var=output
    
    - fail:
        msg: "Failed to fetch protection group details."
      when: output.status != 200

    - set_fact: 
        workItems: "{{output.json.workItems}}"

    #validation for attaching policy to a client
    - debug: 
        msg: "Client is already added to existing group."
      when: item in workItems
      with_items: "{{clientId}}"

    - debug: var=clientId

    #Adding client to policy 
    - name: Adding clientId to workItem
      set_fact: 
        workItems: "{{ workItems + [item] }}"
      when: item not in workItems
      with_items: "{{clientId}}"

    - debug: var=workItems

    - name: Adding client to a specific policy
      uri: 
        url: https://{{endpoint}}:9090/nwrestapi/v3/global/protectiongroups/{{protection_group}}
        method: PUT
        user: "{{username}}"
        password: "{{password}}"
        validate_certs: no
        headers:
          Accept: "application/json"
        body:
          workItems: "{{ workItems }}"
        body_format: json   
        status_code: 401,204,404         
      register: output
    - debug: var=output

    - debug:
        msg: "Successfully added client to the specified protection group"
      when: output.status == 204
    
    - debug:
        msg: "Failed to added client to the specified protection group"
      when: output.status != 204
